### ISSUE TITLE
Deserialize GLTF properties like scene and animations

### ISSUE THREAD

**Issue by bolanzach** [asny/three-d-asset#13]
I want to be able to deserialize additional properties from GLTF files. Particularly `animations` is useful so that consumers of three-d can build their own animation flows for games etc.

Examples
[rust gltf](https://docs.rs/gltf/latest/gltf/)
[three js](https://threejs.org/docs/#examples/en/loaders/GLTFLoader)

@asny is this something you have considered or would be willing to take submissions for?

**Comment by asny** [comment]
Yes, definitely 👍 There's a lot of things that should be supported in `three-d-asset` that isn't yet and animations are definitely one of them. And contributions are more than welcome 🙂 

I guess it's also a prerequisite for https://github.com/asny/three-d/issues/89.

**Comment by asny** [comment]
FYI, started working on this in the [animation](https://github.com/asny/three-d-asset/tree/animation) branch, but will probably take a while 💪

**Comment by zbolan** [comment]
Incredible! You beat me to it! I had only made slow progress as I'm not super familiar with the implementation yet, looking forward to it!

**Comment by asny** [comment]
Added in #14
