### ISSUE TITLE
trying to deserialize .obj -- always getting error

### ISSUE THREAD

**Issue by briteroses** [asny/three-d-asset#23]
Hi, I'm writing an application where I load in a 3d model from a .obj and display it with translations/rotations in a larger 3d environment. I can call three_d_asset::io::load fine, and the result of that looks like

`RawAssets { path: "assets/smallbot.obj", byte length: 309786 }`

However, the deserialize -> unwrap call always gives me an error:

`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: FeatureMissing("obj")'`

I've tried passing in many things to deserialize, including "", "smallbot.obj", and the same path variable I passed into load(), but I always get this error. Is there a bug, or am I doing something wrong?

**Comment by asny** [comment]
As the error says, you didn't enable the obj feature 🙂 you need to specify the three-d-asset dependency like this: 

```
three-d-asset = {version="0.6", features=["obj"]}
```
