### ISSUE TITLE
crash when a viewer is resized to zero

### ISSUE THREAD

**Issue by paul2t** [asny/three-d-asset#39]
`panic` is called at this line when the viewer is reduced to a size of 0.
https://github.com/asny/three-d-asset/blob/319c6f0721c6b2fb586cdb7e42ed28636633a25a/src/camera.rs#L555

I guess it shouldn't happen if we set a height of at least 1.
Maybe `unwrap_or_default` should be called instead. Just in case.

**Comment by asny** [comment]
Bit of an edge case, but yeah, you're right, better safe than sorry 🙂 Fixed in https://github.com/asny/three-d-asset/commit/7473c05a9464a0d7ec07a993c1bc494214c7e419
